# Generated by Django 6.0.6 on 2026-06-19 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jarvis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesion',
            name='actualizada_en',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='sesion',
            name='titulo',
            field=models.CharField(default='Nueva conversación', max_length=200),
        ),
    ]
